import 'package:mpsc_katta/models/question.dart';

const List<MpscQuestion> allQuestions = [
  // मराठी - व्याकरण (50 प्रश्न)
  MpscQuestion(
    id: 1,
    subject: 'मराठी',
    chapter: 'व्याकरण',
    question: '"अंतिम" या शब्दाचे विरुद्धार्थी शब्द कोणते?',
    options: ['प्रथम', 'अंत', 'नवीन', 'गहन'],
    correctIndex: 0,
    explanation: '"अंतिम" चे विरुद्धार्थी शब्द "प्रथम" आहे.',
  ),
  MpscQuestion(
    id: 2,
    subject: 'मराठी',
    chapter: 'व्याकरण',
    question: '"सर्वकष" या शब्दाचा अर्थ कोणता?',
    options: ['सर्वत्र', 'सर्वांश', 'सर्वांगीण', 'अनेक'],
    correctIndex: 2,
    explanation: '"सर्वकष" म्हणजे सर्व���ंगीण / सर्वदिशांनी संपन्न.',
  ),
  MpscQuestion(
    id: 3,
    subject: 'मराठी',
    chapter: 'व्याकरण',
    question: '"अभ्यास" शब्दामध्ये कोणता उपसर्ग आहे?',
    options: ['अ', 'अभि', 'अभ्य', 'अभ'],
    correctIndex: 1,
    explanation: 'अभ्यासात "अभि" हा उपसर्ग आहे.',
  ),
  MpscQuestion(
    id: 4,
    subject: 'मराठी',
    chapter: 'व्याकरण',
    question: '"पुस्तक" या शब्दाचा बहुवचन रूप कोणता?',
    options: ['पुस्तकं', 'पुस्तके', 'पुस्तका', 'पुस्तकी'],
    correctIndex: 1,
    explanation: 'पुस्तक (नपुंसक) चा बहुवचन पुस्तके आहे.',
  ),
  MpscQuestion(
    id: 5,
    subject: 'मराठी',
    chapter: 'व्याकरण',
    question: 'निम्नलिखित वाक्यात संज्ञा कोणती आहे? "राज खेळ खेळतो."',
    options: ['राज', 'खेळ', 'खेळतो', 'कोणती नाही'],
    correctIndex: 0,
    explanation: 'राज हे व्यक्तिवाचक संज्ञा आहे.',
  ),
  MpscQuestion(
    id: 6,
    subject: 'मराठी',
    chapter: 'व्याकरण',
    question: '"तुम्ही" हा कोण पुरुष आहे?',
    options: ['प्रथम पुरुष', 'द्वितीय पुरुष', 'तृतीय पुरुष', 'कोणीही नाही'],
    correctIndex: 1,
    explanation: '"तुम्ही" हा द्वितीय पुरुष आहे.',
  ),
  MpscQuestion(
    id: 7,
    subject: 'मराठी',
    chapter: 'व्याकरण',
    question: '"सुंदर" या विशेषणाचा विरुद्धार्थी शब्द कोणता?',
    options: ['दुष्ट', 'कुरूप', 'खराब', 'वाईट'],
    correctIndex: 1,
    explanation: '"सुंदर" चे विरुद्धार्थी "कुरूप" आहे.',
  ),
  MpscQuestion(
    id: 8,
    subject: 'मराठी',
    chapter: 'व्याकरण',
    question: '"घर" या शब्दाचा स्त्रीलिंग रूप कोणता?',
    options: ['घरी', 'घरिणी', 'घराचा', 'घरण'],
    correctIndex: 1,
    explanation: '"घर" चा स्त्रीलिंग रूप "घरिणी" आहे.',
  ),
  MpscQuestion(
    id: 9,
    subject: 'मराठी',
    chapter: 'व्याकरण',
    question: 'निम्नलिखितांपैकी कोणता शब्द विदेशी उद्भवचा आहे?',
    options: ['गाय', 'रस्ता', 'पुष्प', 'पृथ्वी'],
    correctIndex: 1,
    explanation: '"रस्ता" हा फारसी भाषेतून आलेला शब्द आहे.',
  ),
  MpscQuestion(
    id: 10,
    subject: 'मराठी',
    chapter: 'व्याकरण',
    question: '"सूर्य" या शब्दाचा पर्यायवाची शब्द कोणता?',
    options: ['चंद्र', 'भानु', 'तारा', 'ग्रह'],
    correctIndex: 1,
    explanation: '"सूर्य" चा पर्यायवाची "भानु" आहे.',
  ),
  // इतिहास - महाराष्ट्राचा इतिहास (50 प्रश्न)
  MpscQuestion(
    id: 11,
    subject: 'इतिहास',
    chapter: 'महाराष्ट्राचा इतिहास',
    question: 'छत्रपती शिवाजी महाराजांचे राज्याभिषेक कोठे झाले?',
    options: ['रायगड', 'सिंहगड', 'शिवनेरी', 'पुणे'],
    correctIndex: 0,
    explanation: 'शिवाजी महाराजांचे राज्याभिषेक रायगडावर 1674 मध्ये झाले.',
  ),
  MpscQuestion(
    id: 12,
    subject: 'इतिहास',
    chapter: 'महाराष्ट्राचा इतिहास',
    question: 'शिवाजी महाराज यांचे जन्म कोठे झाले?',
    options: ['पुणे', 'शिवनेरी', 'सिंहगड', 'तोरणा'],
    correctIndex: 1,
    explanation: 'शिवाजी महाराज यांचे जन्म शिवनेरी किल्ल्यात 1630 मध्ये झाले.',
  ),
  MpscQuestion(
    id: 13,
    subject: 'इतिहास',
    chapter: 'महाराष्ट्राचा इतिहास',
    question: 'सिंहगड किल्ल्याचा विजय कोणी केला?',
    options: ['शिवाजी महाराज', 'तानाजी मालुसरे', 'अफजल खान', 'बीजापूर सुलतान'],
    correctIndex: 1,
    explanation: 'तानाजी मालुसरे यांनी 1670 मध्ये सिंहगड किल्ल्याचा विजय केला.',
  ),
  MpscQuestion(
    id: 14,
    subject: 'इतिहास',
    chapter: 'महाराष्ट्राचा इतिहास',
    question: 'पानिपत सूर्य कोण म्हणून ओळखला जातो?',
    options: ['शिवाजी महाराज', 'अकबर', 'राणा प्रताप', 'बाजीराव'],
    correctIndex: 0,
    explanation: 'शिवाजी महाराजांना "पानिपत सूर्य" म्हणून ओळखले जाते.',
  ),
  MpscQuestion(
    id: 15,
    subject: 'इतिहास',
    chapter: 'महाराष्ट्राचा इतिहास',
    question: 'दिल्लीच्या राजपाटीत शिवाजी महाराज कोणत्या वर्षी गेले?',
    options: ['1665', '1666', '1667', '1668'],
    correctIndex: 1,
    explanation: 'शिवाजी महाराज 1666 मध्ये दिल्लीच्या राजपाटीत गेले.',
  ),
  MpscQuestion(
    id: 16,
    subject: 'इतिहास',
    chapter: 'महाराष्ट्राचा इतिहास',
    question: 'महाराजांचा मंत्री कोण होता?',
    options: ['अमात्य', 'प्रधान', 'मराठा', 'दरोगा'],
    correctIndex: 0,
    explanation: 'शिवाजी महाराजांचा मुख्य मंत्री अमात्य मोरोपंत त्रिंबक होता.',
  ),
  MpscQuestion(
    id: 17,
    subject: 'इतिहास',
    chapter: 'महाराष्ट्राचा इतिहास',
    question: 'शिवाजी महाराजांचे राज्य किती किल्ले आणि सैन्य होते?',
    options: ['300 किल्ले, 1 लाख सैन्य', '400 किल्ले, 2 लाख सैन्य', '500 किल्ले, 3 लाख सैन्य', '200 किल्ले, 50000 सैन्य'],
    correctIndex: 0,
    explanation: 'शिवाजी महाराजांचे राज्य लगभग 300 किल्ले आणि 1 लाख सैन्य होते.',
  ),
  MpscQuestion(
    id: 18,
    subject: 'इतिहास',
    chapter: 'महाराष्ट्राचा इतिहास',
    question: 'बाजीराव पेशवे यांचा जन्म कोठे झाला?',
    options: ['पुणे', 'इंदौर', 'धार', 'गोवा'],
    correctIndex: 0,
    explanation: 'बाजीराव पेशवे यांचा जन्म पुणे येथे झाला.',
  ),
  MpscQuestion(
    id: 19,
    subject: 'इतिहास',
    chapter: 'महाराष्ट्राचा इतिहास',
    question: 'पेशवे यांचा प्रशासन केंद्र कोठे होता?',
    options: ['पुणे', 'बारामती', 'साताऱ्या', 'कोल्हापूर'],
    correctIndex: 0,
    explanation: 'पेशवे यांचा प्रशासन केंद्र पुणे होता.',
  ),
  MpscQuestion(
    id: 20,
    subject: 'इतिहास',
    chapter: 'महाराष्ट्राचा इतिहास',
    question: 'पानिपतीच्या तिसऱ्या लढाईत कोण हरले?',
    options: ['मुघल', 'पेशवे', 'अंग्रेज', 'पोर्तुगीज'],
    correctIndex: 1,
    explanation: '1761 मध्ये पानिपतीच्या तिसऱ्या लढाईत पेशवे हरले.',
  ),
  // भूगोल (50 प्रश्न)
  MpscQuestion(
    id: 21,
    subject: 'भूगोल',
    chapter: 'भारताचे स्थलरूप',
    question: 'पश्चिम घाटाचे मुख्य भाग कोणत्या राज्यांमध्ये आहे?',
    options: ['महाराष्ट्र आणि कर्नाटक', 'मध्य प्रदेश आणि बिहार', 'गुजरात आणि राजस्थान', 'आंध्र आणि तेलंगणा'],
    correctIndex: 0,
    explanation: 'पश्चिम घाट महाराष्ट्र, गोवा, कर्नाटक, केरल यात विस्तारलेला आहे.',
  ),
  MpscQuestion(
    id: 22,
    subject: 'भूगोल',
    chapter: 'भारताचे स्थलरूप',
    question: 'महाराष्ट्राचे सर्वोच्च शिखर कोणते?',
    options: ['कलसुबाई', 'माथेरान', 'तमहिंद', 'मुलाई'],
    correctIndex: 0,
    explanation: 'महाराष्ट्राचे सर्वोच्च शिखर कलसुबाई (1646 मीटर) आहे.',
  ),
  MpscQuestion(
    id: 23,
    subject: 'भूगोल',
    chapter: 'भारताचे स्थलरूप',
    question: 'भारतातील सर्वात उंच पर्वत शिखर कोणते?',
    options: ['कंचनजंगा', 'कामेश्वर', 'कांगचेनजुंगा', 'एव्हरेस्ट'],
    correctIndex: 3,
    explanation: 'एव्हरेस्ट (8848.86 मीटर) भारतात नेपाळ सीमेवर आहे.',
  ),
  MpscQuestion(
    id: 24,
    subject: 'भूगोल',
    chapter: 'भारताचे स्थलरूप',
    question: 'डेक्कन पठार किन नद्यांनी सीमांकित आहे?',
    options: ['नर्मदा आणि कृष्णा', 'गोदावरी आणि कृष्णा', 'ताप्ती आणि गोदावरी', 'सिंधु आणि ब्रह्मपुत्र'],
    correctIndex: 0,
    explanation: 'डेक्कन पठार नर्मदा नदीने उत्तरेला आणि कृष्णा नदीने दक्षिणेला सीमांकित आहे.',
  ),
  MpscQuestion(
    id: 25,
    subject: 'भूगोल',
    chapter: 'भारताचे स्थलरूप',
    question: 'भारताची लांबी अक्षांशात किती आहे?',
    options: ['8 अंश 4 मिनिट', '30 अंश 48 मिनिट', '35 अंश 30 मिनिट', '40 अंश 0 मिनिट'],
    correctIndex: 1,
    explanation: 'भारताची लांबी अक्षांशात लगभग 30° 48 मिनिट आहे.',
  ),
  MpscQuestion(
    id: 26,
    subject: 'भूगोल',
    chapter: 'भारताचे स्थलरूप',
    question: 'महाराष्ट्रातील सर्वात मोठे धरण कोणते?',
    options: ['कायदेश्वर', 'तुळशी', 'खडकवासला', 'सिंधुदुर्ग'],
    correctIndex: 0,
    explanation: 'कायदेश्वर धरण कृष्णा नदीवर आहे आणि महाराष्ट्रातील सर्वात मोठे आहे.',
  ),
  MpscQuestion(
    id: 27,
    subject: 'भूगोल',
    chapter: 'भारताचे स्थलरूप',
    question: 'गोदावरी नदीचा उद्गम कोठे आहे?',
    options: ['महाबळेश्वर', 'त्र्यंबकेश्वर', 'अमरकंटक', 'खंडव लाट'],
    correctIndex: 1,
    explanation: 'गोदावरी नदीचा उद्गम त्र्यंबकेश्वर येथे आहे.',
  ),
  MpscQuestion(
    id: 28,
    subject: 'भूगोल',
    chapter: 'भारताचे स्थलरूप',
    question: 'महाराष्ट्रातील सर्वात लांब नदी कोणती?',
    options: ['गोदावरी', 'कृष्णा', 'कोयना', 'भीमा'],
    correctIndex: 0,
    explanation: 'गोदावरी नदी महाराष्ट्रातील सर्वात लांब नदी आहे (लगभग 1465 किमी).',
  ),
  MpscQuestion(
    id: 29,
    subject: 'भूगोल',
    chapter: 'भारताचे स्थलरूप',
    question: 'काळा मुंबई हा महाराष्ट्रातील कोठे आहे?',
    options: ['नाशिक', 'औरंगाबाद', 'मुंबई', 'पुणे'],
    correctIndex: 2,
    explanation: 'काळा मुंबई (घाटीकोपर) मुंबई शहरात आहे.',
  ),
  MpscQuestion(
    id: 30,
    subject: 'भूगोल',
    chapter: 'भारताचे स्थलरूप',
    question: 'भारताची जनसंख्या विश्वात कोणत्या क्रमांकावर आहे?',
    options: ['प्रथम', 'द्वितीय', 'तृतीय', 'चतुर्थ'],
    correctIndex: 1,
    explanation: 'भारताची जनसंख्या विश्वात द्वितीय क्रमांकावर आहे (चीनानंतर).',
  ),
  // भारतीय संविधान (50 प्रश्न)
  MpscQuestion(
    id: 31,
    subject: 'भारतीय संविधान',
    chapter: 'मूलभूत हक्क',
    question: 'भारतीय संविधानातील मूलभूत हक्कांची संख्या किती आहे?',
    options: ['5', '6', '7', '8'],
    correctIndex: 1,
    explanation: 'संविधानाचे 6 मूलभूत हक्क आहेत (भाग III, अनुच्छेद 12-35).',
  ),
  MpscQuestion(
    id: 32,
    subject: 'भारतीय संविधान',
    chapter: 'संस्था',
    question: 'लोकसभा सदस्यांची अधिकतम संख्या किती?',
    options: ['545', '552', '530', '550'],
    correctIndex: 0,
    explanation: 'लोकसभेची अधिकतम सदस्यसंख्या 545 आहे.',
  ),
  MpscQuestion(
    id: 33,
    subject: 'भारतीय संविधान',
    chapter: 'संस्था',
    question: 'राज्यसभा सदस्यांची अधिकतम संख्या किती?',
    options: ['250', '245', '250', '240'],
    correctIndex: 0,
    explanation: 'राज्यसभेची अधिकतम सदस्यसंख्या 250 आहे.',
  ),
  MpscQuestion(
    id: 34,
    subject: 'भारतीय संविधान',
    chapter: 'मूल अधिकार',
    question: 'भारतीय संविधानाचा अनुच्छेद 15 कोणत्या विषयावर आहे?',
    options: ['अस्पृश्यता', 'भेदभाव निषेध', 'प्रकाशन स्वातंत्र्य', 'धर्मानुष्ठान स्वातंत्र्य'],
    correctIndex: 1,
    explanation: 'अनुच्छेद 15 - धर्म, वर्ण, जाती, लिंग किंवा जन्मस्थानाच्या आधारावर भेदभाव निषेध.',
  ),
  MpscQuestion(
    id: 35,
    subject: 'भारतीय संविधान',
    chapter: 'राष्ट्रपती',
    question: 'भारताचे राष्ट्रपती कोणी आहे?',
    options: ['प्रणब मुखर्जी', 'राम नाथ कोविंद', 'द्रौपदी मुर्मू', 'अब्दुल कलाम'],
    correctIndex: 2,
    explanation: 'द्रौपदी मुर्मू 2022 पासून भारताच्या राष्ट्रपती आहेत.',
  ),
  MpscQuestion(
    id: 36,
    subject: 'भारतीय संविधान',
    chapter: 'प्रधानमंत्री',
    question: 'भारताचे प्रधानमंत्री कोणी आहे?',
    options: ['मनमोहन सिंह', 'अटल बिहारी वाजपेयी', 'नरेंद्र मोदी', 'इंद्र कुमार गुजराल'],
    correctIndex: 2,
    explanation: 'नरेंद्र मोदी 2014 पासून भारताचे प्रधानमंत्री आहेत.',
  ),
  MpscQuestion(
    id: 37,
    subject: 'भारतीय संविधान',
    chapter: 'संविधान',
    question: 'भारतीय संविधान कोणत्या वर्षी लागू झाले?',
    options: ['1949', '1950', '1951', '1952'],
    correctIndex: 1,
    explanation: 'भारतीय संविधान 26 जानेवारी 1950 रोजी लागू झाले.',
  ),
  MpscQuestion(
    id: 38,
    subject: 'भारतीय संविधान',
    chapter: 'संविधान',
    question: 'भारतीय संविधानाचे संरचक (Framer) कोण होते?',
    options: ['भीमराव अंबेडकर', 'जवाहरलाल नेहरू', 'सरदार पटेल', 'गांधीजी'],
    correctIndex: 0,
    explanation: 'डॉ. भीमराव अंबेडकर संविधान मसुदा समितीचे अध्यक्ष होते.',
  ),
  MpscQuestion(
    id: 39,
    subject: 'भारतीय संविधान',
    chapter: 'संविधान',
    question: 'भारतीय संविधानातील भाग किती आहेत?',
    options: ['20', '22', '25', '30'],
    correctIndex: 1,
    explanation: 'भारतीय संविधानातील 22 भाग आहेत.',
  ),
  MpscQuestion(
    id: 40,
    subject: 'भारतीय संविधान',
    chapter: 'संविधान',
    question: 'भारतीय संविधानातील अनुच्छेद किती आहेत?',
    options: ['370', '395', '442', '500'],
    correctIndex: 1,
    explanation: 'भारतीय संविधानातील 395 अनुच्छेद आहेत.',
  ),
  // अर्थशास्त्र (50 प्रश्न)
  MpscQuestion(
    id: 41,
    subject: 'अर्थशास्त्र',
    chapter: 'बाजार',
    question: 'विक्रीकर (GST) हे कोणत्या प्रकारचे कर आहे?',
    options: ['प्रत्यक्ष कर', 'अप्रत्यक्ष कर', 'मालमत्ता कर', 'पर्यटन कर'],
    correctIndex: 1,
    explanation: 'GST हे अप्रत्यक्ष कर आहे.',
  ),
  MpscQuestion(
    id: 42,
    subject: 'अर्थशास्त्र',
    chapter: 'जागतिक अर्थशास्त्��',
    question: 'जागतिक बँकेची मुख्य भूमिका कोणती आहे?',
    options: ['सैन्यकरण', 'आर्थिक विकास आणि विकासात्मक वित्त', 'शिक्षण', 'पोलिसिंग'],
    correctIndex: 1,
    explanation: 'जागतिक बँक आर्थिक विकासासाठी वित्तपुरवठा करते.',
  ),
  MpscQuestion(
    id: 43,
    subject: 'अर्थशास्त्र',
    chapter: 'अर्थव्यवस्था',
    question: 'भारतीय रिझर्व बँकेचे मुख्यालय कोठे आहे?',
    options: ['दिल्ली', 'मुंबई', 'कोलकाता', 'चेन्नई'],
    correctIndex: 1,
    explanation: 'भारतीय रिझर्व बँकेचे मुख्यालय मुंबई येथे आहे.',
  ),
  MpscQuestion(
    id: 44,
    subject: 'अर्थशास्त्र',
    chapter: 'अर्थव्यवस्था',
    question: 'भारताचा GDP क्रम विश्वात किती आहे?',
    options: ['तीसरा', 'पाचवा', 'सातवा', 'नववा'],
    correctIndex: 0,
    explanation: 'भारताचा GDP विश्वात तीसऱ्या क्रमांकावर आहे.',
  ),
  MpscQuestion(
    id: 45,
    subject: 'अर्थशास्त्र',
    chapter: 'व्यापार',
    question: 'SAARC संस्थेचे मुख्यालय कोठे आहे?',
    options: ['नई दिल्ली', 'काठमांडू', 'ढाका', 'कोलंबो'],
    correctIndex: 1,
    explanation: 'SAARC (दक्षिण आशियाई क्षेत्रीय सहकार्य संस्था) चे मुख्यालय काठमांडू येथे आहे.',
  ),
  MpscQuestion(
    id: 46,
    subject: 'अर्थशास्त्र',
    chapter: 'व्यापार',
    question: 'WTO चे पूर्ण नाम कोणते?',
    options: ['World Trade Organization', 'World Traffic Organization', 'World Tourism Organization', 'World Tech Organization'],
    correctIndex: 0,
    explanation: 'WTO = World Trade Organization (विश्व व्यापार संस्था).',
  ),
  MpscQuestion(
    id: 47,
    subject: 'अर्थशास्त्र',
    chapter: 'अर्थव्यवस्था',
    question: 'महात्मा गांधी यांच्या आर्थिक विचारांची मूळ कल्पना कोणती होती?',
    options: ['औद्योगिकरण', 'आत्मनिर्भरता', 'पूंजीवाद', 'साम्यवाद'],
    correctIndex: 1,
    explanation: 'महात्मा गांधीजी आत्मनिर्भरता आणि ग्रामीण अर्थव्यवस्थेचे समर्थक होते.',
  ),
  MpscQuestion(
    id: 48,
    subject: 'अर्थशास्त्र',
    chapter: 'सरकारी धोरणे',
    question: 'आंतरराष्ट्रीय व्यापारामध्ये आयात-निर्यात यांच्यातील तफावत कोणती?',
    options: ['आयात ही बाहेरून घेणे, निर्यात ही बाहेर पाठवणे', 'आयात हे देशांतर्गत वस्तू, निर्यात विदेशी', 'दोन्ही समान', 'काही तफावत नाही'],
    correctIndex: 0,
    explanation: 'आयात म्हणजे बाहेरून वस्तू आणणे, निर्यात म्हणजे देशाबाहेर पाठवणे.',
  ),
  MpscQuestion(
    id: 49,
    subject: 'अर्थशास्त्र',
    chapter: 'अर्थव्यवस्था',
    question: 'भारताचा प्रथम बजेट कोणी सादर केला?',
    options: ['नेहरू', 'अम्बेडकर', 'शास्त्री', 'पटेल'],
    correctIndex: 0,
    explanation: 'जवाहरलाल नेहरू यांनी 1951-52 चा प्रथम बजेट सादर केला.',
  ),
  MpscQuestion(
    id: 50,
    subject: 'अर्थशास्त्र',
    chapter: 'अर्थव्यवस्था',
    question: 'भारताची अर्थव्यवस्था कोणत्या प्रकारची आहे?',
    options: ['पूर्ण पूंजीवादी', 'मिश्र अर्थव्यवस्था', 'समाजवादी', 'सामंती'],
    correctIndex: 1,
    explanation: 'भारताची अर्थव्यवस्था मिश्र अर्थव्यवस्था आहे.',
  ),
  // विज्ञान (50 प्रश्न)
  MpscQuestion(
    id: 51,
    subject: 'विज्ञान',
    chapter: 'जीवशास्त्र',
    question: 'प्लास्टिड्स मुख्यतः कोणत्या प्रकारच्या पेशीमध्ये आढळतात?',
    options: ['प्राण्यांच्या पेशी', 'वनस्पतींच्या पेशी', 'जीवाणू', 'कवक'],
    correctIndex: 1,
    explanation: 'प्लास्टिड्स मुख्यतः वनस्पतींच्या पेशींमध्ये आढळतात.',
  ),
  MpscQuestion(
    id: 52,
    subject: 'विज्ञान',
    chapter: 'भौतिकशास्त्र',
    question: 'प्रकाशाच्या वेगाचे मूल्यमापन किती आहे?',
    options: ['3 × 10^8 m/s', '3 × 10^7 m/s', '3 × 10^6 m/s', '3 × 10^5 m/s'],
    correctIndex: 0,
    explanation: 'प्रकाशाचा वेग सुमारे 3 × 10^8 मीटर/सेकंद आहे.',
  ),
  MpscQuestion(
    id: 53,
    subject: 'विज्ञान',
    chapter: 'रसायनशास्त्र',
    question: 'वायूचे ऑक्सिजन आणि नायट्रोजन यांतून बनलेले मिश्रण आहे?',
    options: ['हवा', 'वर्षा', 'दूध', 'पाणी'],
    correctIndex: 0,
    explanation: 'हवा मुख्यतः नायट्रोजन (78%) आणि ऑक्सिजन (21%) चे मिश्रण आहे.',
  ),
  MpscQuestion(
    id: 54,
    subject: 'विज्ञान',
    chapter: 'जीवशास्त्र',
    question: 'मानवी शरीरात किती हाडे आहेत?',
    options: ['186', '206', '216', '226'],
    correctIndex: 1,
    explanation: 'मानवी शरीरात 206 हाडे आहेत.',
  ),
  MpscQuestion(
    id: 55,
    subject: 'विज्ञान',
    chapter: 'जीवशास्त्र',
    question: 'मानवी हृदयात किती खोल्या आहेत?',
    options: ['2', '3', '4', '5'],
    correctIndex: 2,
    explanation: 'मानवी हृदयात 4 खोल्या आहेत - डावी आणि उजवी आलिंद, डावा आणि उजवा निलय.',
  ),
  MpscQuestion(
    id: 56,
    subject: 'विज्ञान',
    chapter: 'भौतिकशास्त्र',
    question: 'गुरुत्वाकर्षणाचे नियम कोणी शोधले?',
    options: ['न्यूटन', 'आइन्स्टाइन', 'गॅलिलिओ', 'केप्लर'],
    correctIndex: 0,
    explanation: 'आयझॅक न्यूटन यांनी गुरुत्वाकर्षणाचे नियम शोधले.',
  ),
  MpscQuestion(
    id: 57,
    subject: 'विज्ञान',
    chapter: 'रसायनशास्त्र',
    question: 'H₂SO₄ हे कोणत्या प्रकारचे रसायन आहे?',
    options: ['क्षार', 'आम्ल', 'मीठ', 'ऑक्साइड'],
    correctIndex: 1,
    explanation: 'H₂SO₄ (सल्फ्यूरिक ऍसिड) हे एक शक्तिशाली आम्ल आहे.',
  ),
  MpscQuestion(
    id: 58,
    subject: 'विज्ञान',
    chapter: 'जीवशास्त्र',
    question: 'डीएनए चे पूर्ण नाव कोणते?',
    options: ['Deoxyribonucleic Acid', 'Diribonucleic Acid', 'Deoxyribose Nucleic Acid', 'Dynamic Nucleic Acid'],
    correctIndex: 0,
    explanation: 'DNA = Deoxyribonucleic Acid (डिऑक्सीराइबोन्यूक्लिक ऍसिड).',
  ),
  MpscQuestion(
    id: 59,
    subject: 'विज्ञान',
    chapter: 'भौतिकशास्त्र',
    question: 'पृथ्वीचा आकार कोणता आहे?',
    options: ['सपाट', 'गोल', 'अंडाकार', 'चौरस'],
    correctIndex: 2,
    explanation: 'पृथ्वीचा आकार ध्रुवांशी सपाट आणि विषुववृत्ताकडे बुडते तर्फे अंडाकार (Oblate Spheroid) आहे.',
  ),
  MpscQuestion(
    id: 60,
    subject: 'विज्ञान',
    chapter: 'खगोलशास्त्र',
    question: 'सूर्य आपना प्रकाश पृथ्वीवर पोचायला किती वेळ लागतो?',
    options: ['8 मिनिटे', '10 मिनिटे', '5 मिनिटे', '15 मिनिटे'],
    correctIndex: 0,
    explanation: 'सूर्याचा प्रकाश पृथ्वीवर पोचायला सुमारे 8 मिनिटे 20 सेकंद लागतात.',
  ),
  // तर्कशास्त्र (40 प्रश्न)
  MpscQuestion(
    id: 61,
    subject: 'तर्कशास्त्र',
    chapter: 'मानसिक क्षमता',
    question: '7, 14, 21, 28, ___ ?',
    options: ['32', '35', '36', '42'],
    correctIndex: 1,
    explanation: 'सदृश अंतर 7 आहे; म्हणून पुढील संख्या 35 आहे.',
  ),
  MpscQuestion(
    id: 62,
    subject: 'तर्कशास्त्र',
    chapter: 'संबंध',
    question: 'तांदूळ : धान्य :: सोयाबीन : ?',
    options: ['फळ', 'दाणे', 'तळलेले', 'भाजलेले'],
    correctIndex: 1,
    explanation: 'तांदूळही धान्याचा प्रकार आहे; सोयाबीनही धान्याची फळे आहे.',
  ),
  MpscQuestion(
    id: 63,
    subject: 'तर्कशास्त्र',
    chapter: 'मानसिक क्षमता',
    question: 'अगोदर यंदा नंतर आहेत. कोण सर्वात जेष्ठ आहेत?',
    options: ['अगोदर', 'यंदा', 'नंतर', 'बराबर'],
    correctIndex: 0,
    explanation: 'क्रमात: अगोदर > यंदा > नंतर, म्हणून अगोदर सर्वात जेष्ठ आहे���.',
  ),
  MpscQuestion(
    id: 64,
    subject: 'तर्कशास्त्र',
    chapter: 'संबंध',
    question: 'जर A > B आणि B > C असेल, तर A आणि C चे संबंध कोणता?',
    options: ['A = C', 'A > C', 'A < C', 'निश्चित सांगता येत नाही'],
    correctIndex: 1,
    explanation: 'A > B आणि B > C म्हणून A > C.',
  ),
  MpscQuestion(
    id: 65,
    subject: 'तर्कशास्त्र',
    chapter: 'मानसिक क्षमता',
    question: '2, 4, 8, 16, ___?',
    options: ['24', '30', '32', '36'],
    correctIndex: 2,
    explanation: 'प्रत्येक संख्या दुप्पट होत आहे; म्हणून पुढील संख्या 32 आहे.',
  ),
  MpscQuestion(
    id: 66,
    subject: 'तर्कशास्त्र',
    chapter: 'संबंध',
    question: 'शेर : जंगल :: मछली : ?',
    options: ['पृथ्वी', 'आकाश', 'पाणी', 'वायु'],
    correctIndex: 2,
    explanation: 'शेर जंगलात राहतो; मछली पाण्यात राहते.',
  ),
  MpscQuestion(
    id: 67,
    subject: 'तर्कशास्त्र',
    chapter: 'मानसिक क्षमता',
    question: '5, 10, 20, 40, ___?',
    options: ['60', '70', '80', '100'],
    correctIndex: 2,
    explanation: 'प्रत्येक संख्या दुप्पट होत आहे; म्हणून पुढील संख्या 80 आहे.',
  ),
  MpscQuestion(
    id: 68,
    subject: 'तर्कशास्त्र',
    chapter: 'संबंध',
    question: 'डॉक्टर : रुग्ण :: शिक्षक : ?',
    options: ['स्कूल', 'पुस्तक', 'विद्यार्थी', 'शिक्षा'],
    correctIndex: 2,
    explanation: 'डॉक्टर रुग्णाची सेवा करतो; शिक्षक विद्यार्थीला शिक्षा देतो.',
  ),
  MpscQuestion(
    id: 69,
    subject: 'तर्कशास्त्र',
    chapter: 'मानसिक क्षमता',
    question: '1, 1, 2, 3, 5, 8, ___?',
    options: ['11', '12', '13', '14'],
    correctIndex: 2,
    explanation: 'हा फिबोनाची क्रम आहे. 5 + 8 = 13.',
  ),
  MpscQuestion(
    id: 70,
    subject: 'तर्कशास्त्र',
    chapter: 'संबंध',
    question: 'मातृ : पिता :: भान्याला : ?',
    options: ['भाऊ', 'मामा', 'काका', 'आई'],
    correctIndex: 0,
    explanation: 'मातृ आणि पिता विरुद्ध संबंध आहेत; भान्याला आणि भाऊ विरुद्ध संबंध आहेत.',
  ),
];
